// Code generated by sqlc. DO NOT EDIT.

package mysql

import (
	"time"
)

type Exchange struct {
	ID             int64
	CreatedAt      time.Time
	Amount         float64
	Rate           float64
	FromCurrency   string
	ToCurrency     string
	ConvertedValue float64
	CurrencySymbol string
}
