CREATE TABLE IF NOT EXISTS exchanges (
	id BIGINT NOT NULL AUTO_INCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	amount DOUBLE PRECISION(64,2) NOT NULL,
	rate  DOUBLE PRECISION(64,5) NOT NULL,
	from_currency VARCHAR(8) NOT NULL,
	to_currency VARCHAR(8) NOT NULL,
	converted_value DOUBLE PRECISION(64,2) NOT NULL,
	currency_symbol VARCHAR(8) NOT NULL,
	PRIMARY KEY (id)
);
